#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

MODE=$1

if [ ! -f $DIR/set_${MODE}.sh ] ; then
    echo "Mode echo \"${DIR}/set_${MODE}.sh\" not found. Use \"low\" or \"high\" instead."
    exit 0
fi

echo "Mode $MODE found. Configuring..."
$DIR/set_${MODE}.sh

