#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"

DELAY=3

OPTS=`getopt -a -o sht:m: -l soft,hard,time:,mode: -- "$@"`
if [ $? != 0 ] ; then echo "Failed parsing options." >&2 ; exit 1 ; fi

while true; do
  case "$1" in
    -s | --soft ) 
        if [ -v "RELOAD" ] ; then echo "Incompatible options." >&2 ; exit 0; fi
        RELOAD=false
        shift ;;
    -h | --hard ) 
        if [ -v "RELOAD" ] ; then echo "Incompatible options." >&2 ; exit 0; fi
        RELOAD=true
        shift ;;
    -m | --mode ) 
        if [ -v "MODE" ] ; then echo "Incompatible options." >&2 ; exit 0; fi
        MODE="$2"
        shift ; shift;;
    -t | --time ) DELAY="$2"; shift; shift ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done


if [ ! -v "RELOAD" ] ; then RELOAD=false ; echo "No options found, soft reload choosed by default." ; fi
if [ ! -v "MODE" ] ; then echo "Mode (low/hi) of DPI settings required." ; exit 0 ; fi

if [ ! -f $SCRIPT_DIR/files/${MODE}dpi.sh ] || [ ! -f $SCRIPT_DIR/files/${MODE}_fonts.conf  ] ; then
    echo "Mode not found."
    exit 0
fi

cp $SCRIPT_DIR/files/${MODE}dpi.sh ~/.xprofile && echo 'copy to xprofile: OK'
cp $SCRIPT_DIR/files/${MODE}_fonts.conf ~/.config/kcmfonts && echo 'copy fonts config: OK'
source ~/.xprofile && echo 'source xprofile: OK'

echo 'Wait for reload...' && sleep $DELAY

if $RELOAD ; then
    sudo systemctl restart sddm
else
    kcminit
    killall plasmashell && nohup kstart5 plasmashell  &>/dev/null &
    nohup kwin_x11 --replace  &>/dev/null &
    killall krunner && nohup krunner &>/dev/null &
    killall yakuake && nohup yakuake &>/dev/null &
    nohup kstartupconfig5 &>/dev/null &
fi
